version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: docker.pkg.github.com/coryball/backend-template/template-server
    networks:
      web:
        aliases:
          - server
      template:
        aliases:
          - server
    stdin_open: true
    tty: true
  postgres:
    container_name: backend_template_database
    image: postgres:13.2
    environment:
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_PORT: $DATABASE_PORT
      PGDATA: /data/postgres
    env_file: .env
    expose:
      - "5432"
    volumes:
      - ./.docker/data/:/data/postgres
      - ./.docker/psql_scripts/:/docker-entrypoint-initdb.d/
    networks:
      template:
        aliases:
          - database
      web:
        aliases:
          - backend-template-database
  redis:
    container_name: redis
    image: redis:alpine3.13
    restart: unless-stopped
    expose:
      - 6379
    networks:
      template:
        aliases:
          - redis
      web:
        aliases:
          - backend-template-redis
    volumes:
      - ./docker/redis:/data
networks:
  web:
    external: true
  template:
    external: false