version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: docker.pkg.github.com/coryball/backend-template/template-server
    networks:
      web:
        aliases:
          - server
      template:
        aliases:
          - server
    env_file:
      - env/dev.env
  postgres:
    container_name: backend_template_database
    image: postgres:13.2
    env_file:
      - env/dev.env
    expose:
      - 5432
    volumes:
      - ./.docker/data/:/data/postgres
      - ./.docker/psql_scripts/:/docker-entrypoint-initdb.d/
    networks:
      template:
        aliases:
          - database
      web:
        aliases:
          - backend-template-database
  redis:
    container_name: redis
    image: redis:alpine3.13
    restart: unless-stopped
    expose:
      - 6379
    networks:
      template:
        aliases:
          - redis
      web:
        aliases:
          - backend-template-redis
    volumes:
      - ./.docker/redis:/data
networks:
  web:
    external: true
  template:
    external: false